##Запрос создания машины
POST http://localhost:8080/api/v1/car: {
  "Network": {
    "addresses": {
      "local": {
        "address": "::1",
        "family": "IPv6",
        "port": 57291
      },
      "remote": {
        "address": "::1",
        "family": "IPv6",
        "port": 8080
      }
    }
  },
  "Request Headers": {
    "content-type": "application/json",
    "authorization": "Basic YWRtaW46cXdlcnR5",
    "user-agent": "PostmanRuntime/7.43.4",
    "accept": "*/*",
    "postman-token": "e4feba75-3018-485c-a959-923fbd50bce3",
    "host": "localhost:8080",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "76"
  },
  "Request Body": "{\r\n    \"brand\": \"LADA\",\r\n    \"model\": \"VESTA\",\r\n    \"number\": \"FE342RU26\"\r\n}",
  "Response Headers": {
    "x-content-type-options": "nosniff",
    "x-xss-protection": "0",
    "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
    "pragma": "no-cache",
    "expires": "0",
    "x-frame-options": "DENY",
    "content-type": "application/json",
    "transfer-encoding": "chunked",
    "date": "Sun, 04 May 2025 12:33:07 GMT",
    "keep-alive": "timeout=60",
    "connection": "keep-alive"
  },
  "Response Body": "{\"id\":7,\"brand\":\"LADA\",\"model\":\"VESTA\",\"number\":\"FE342RU26\"}"
}

##Запрос получение клиента
GET http://localhost:8080/api/v1/client/3: {
  "Network": {
    "addresses": {
      "local": {
        "address": "::1",
        "family": "IPv6",
        "port": 57535
      },
      "remote": {
        "address": "::1",
        "family": "IPv6",
        "port": 8080
      }
    }
  },
  "Request Headers": {
    "content-type": "application/json",
    "authorization": "Basic YWRtaW46cXdlcnR5",
    "user-agent": "PostmanRuntime/7.43.4",
    "accept": "*/*",
    "postman-token": "1397ae13-9d99-48f9-bf8a-71f800e1e05d",
    "host": "localhost:8080",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "76"
  },
  "Request Body": "{\r\n    \"brand\": \"LADA\",\r\n    \"model\": \"VESTA\",\r\n    \"number\": \"FE342RU26\"\r\n}",
  "Response Headers": {
    "x-content-type-options": "nosniff",
    "x-xss-protection": "0",
    "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
    "pragma": "no-cache",
    "expires": "0",
    "x-frame-options": "DENY",
    "content-type": "application/json",
    "transfer-encoding": "chunked",
    "date": "Sun, 04 May 2025 12:36:07 GMT",
    "keep-alive": "timeout=60",
    "connection": "keep-alive"
  },
  "Response Body": "{\"fio\":\"Иванов Иван Иваныч\",\"phone\":\"8 918 345 21 33\",\"dateOfBirth\":null}"
}

##Добавление нового клиента
POST http://localhost:8080/api/v1/client: {
  "Network": {
    "addresses": {
      "local": {
        "address": "::1",
        "family": "IPv6",
        "port": 57776
      },
      "remote": {
        "address": "::1",
        "family": "IPv6",
        "port": 8080
      }
    }
  },
  "Request Headers": {
    "content-type": "application/json",
    "authorization": "Basic YWRtaW46cXdlcnR5",
    "user-agent": "PostmanRuntime/7.43.4",
    "accept": "*/*",
    "postman-token": "18797192-fa02-4e48-b97b-6164fc43ecf3",
    "host": "localhost:8080",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "145"
  },
  "Request Body": "{\r\n    \"fio\": \"Тестовый петр петрович\",\r\n    \"phone\": \"+7 932 433 21 44\",\r\n    \"dateOfBirth\": null,\r\n    \"isDelete\": false\r\n}",
  "Response Headers": {
    "x-content-type-options": "nosniff",
    "x-xss-protection": "0",
    "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
    "pragma": "no-cache",
    "expires": "0",
    "x-frame-options": "DENY",
    "content-type": "application/json",
    "transfer-encoding": "chunked",
    "date": "Sun, 04 May 2025 12:38:40 GMT",
    "keep-alive": "timeout=60",
    "connection": "keep-alive"
  },
  "Response Body": "{\"id\":6,\"fio\":\"Тестовый петр петрович\",\"phone\":\"+7 932 433 21 44\",\"dateOfBirth\":null,\"isDelete\":false}"
}

##Получение заказа
GET http://localhost:8080/api/v1/order/1: {
  "Network": {
    "addresses": {
      "local": {
        "address": "::1",
        "family": "IPv6",
        "port": 57842
      },
      "remote": {
        "address": "::1",
        "family": "IPv6",
        "port": 8080
      }
    }
  },
  "Request Headers": {
    "authorization": "Basic YWRtaW46cXdlcnR5",
    "user-agent": "PostmanRuntime/7.43.4",
    "accept": "*/*",
    "postman-token": "76bd0db4-100c-4479-ad9c-e55fbedce8da",
    "host": "localhost:8080",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive"
  },
  "Response Headers": {
    "x-content-type-options": "nosniff",
    "x-xss-protection": "0",
    "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
    "pragma": "no-cache",
    "expires": "0",
    "x-frame-options": "DENY",
    "content-type": "application/json",
    "transfer-encoding": "chunked",
    "date": "Sun, 04 May 2025 12:39:49 GMT",
    "keep-alive": "timeout=60",
    "connection": "keep-alive"
  },
  "Response Body": "{\"number\":\"AR432RU29\",\"carName\":\"BMWm5\",\"fio\":\"Иванов Иван Иваныч\",\"price\":5000,\"details\":\"Замена 4 колес 20 радиуса\"}"
}

##Добавление заказа
POST http://localhost:8080/api/v1/order: {
  "Network": {
    "addresses": {
      "local": {
        "address": "::1",
        "family": "IPv6",
        "port": 58191
      },
      "remote": {
        "address": "::1",
        "family": "IPv6",
        "port": 8080
      }
    }
  },
  "Request Headers": {
    "content-type": "application/json",
    "authorization": "Basic YWRtaW46cXdlcnR5",
    "user-agent": "PostmanRuntime/7.43.4",
    "accept": "*/*",
    "postman-token": "dcb6f83b-451e-4938-87d5-097421ab829f",
    "host": "localhost:8080",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "410"
  },
  "Request Body": "{\r\n    \"car\": {\r\n        \"id\": 7,\r\n        \"brand\": \"LADA\",\r\n        \"model\": \"VESTA\",\r\n        \"number\": \"FE342RU26\"\r\n    },\r\n    \"client\": {\r\n        \"id\": 6,\r\n        \"fio\": \"Тестовый петр петрович\",\r\n        \"phone\": \"+7 932 433 21 44\",\r\n        \"dateOfBirth\": null,\r\n        \"isDelete\": false\r\n    },\r\n    \"price\": 3000,\r\n    \"details\": \"Замена 4 колес 18 радиуса\"\r\n}",
  "Response Headers": {
    "x-content-type-options": "nosniff",
    "x-xss-protection": "0",
    "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
    "pragma": "no-cache",
    "expires": "0",
    "x-frame-options": "DENY",
    "content-type": "application/json",
    "transfer-encoding": "chunked",
    "date": "Sun, 04 May 2025 12:43:16 GMT",
    "keep-alive": "timeout=60",
    "connection": "keep-alive"
  },
  "Response Body": "{\"id\":4,\"client\":{\"id\":6,\"fio\":\"Тестовый петр петрович\",\"phone\":\"+7 932 433 21 44\",\"dateOfBirth\":null,\"isDelete\":false},\"car\":{\"id\":7,\"brand\":\"LADA\",\"model\":\"VESTA\",\"number\":\"FE342RU26\"},\"price\":3000,\"details\":\"Замена 4 колес 18 радиуса\"}"
}