create SCHEMA IF NOT EXISTS tireService;

create TABLE tireService.client (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fio varchar (255) NOT NULL,
    phone varchar (255) NOT NULL,
    date_of_birth timestamp,
    is_delete BOOLEAN NOT NULL DEFAULT FALSE
);

create TABLE tireService.car (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    brand varchar (255) NOT NULL,
    "model" varchar (255) NOT NULL,
    "number" varchar (255) NOT NULL
);

create TABLE tireService."order" (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client_id INT REFERENCES tireService.client(id),
    car_id INT REFERENCES tireService.car(id),
    price INT NOT NULL,
    details varchar (255)
);