CREATE TABLE IF NOT EXISTS clients (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name varchar(50) NOT NULL,
  midl_name varchar(50) NOT NULL,
  last_name varchar(50) NOT NULL,
  date_of_birth timestamp,
  phone_number int NOT NULL
);

CREATE TABLE IF NOT EXISTS cars (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id int NOT NULL,
  car_name varchar(50) NOT NULL,
  car_model varchar(50) NOT NULL,
  car_number varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cost_of_work int NOT NULL,
  car_id int NOT NULL,
  client_id int NOT NULL
);

INSERT INTO clients (first_name, midl_name, last_name, date_of_birth, phone_number)
VALUES ('Иван', 'Иванович', 'Иванов', '1990-01-01', 12345670),
       ('Петр', 'Петрович', 'Петров', '1985-02-05', 98765430);

INSERT INTO cars (client_id, car_name, car_model, car_number)
VALUES (1,'Toyota', 'Corolla', 'A111AA'),
       (2, 'Mercedes-Benz', 'C-Class', 'B222BB');

INSERT INTO orders (cost_of_work, car_id, client_id)
VALUES (5000, 1, 1),
       (7000, 2, 2);

ALTER TABLE cars ADD CONSTRAINT fk_cars_client FOREIGN KEY (client_id) REFERENCES clients(id);
ALTER TABLE orders ADD CONSTRAINT fk_orders_car FOREIGN KEY (car_id) REFERENCES cars(id);
ALTER TABLE orders ADD CONSTRAINT fk_orders_client FOREIGN KEY (client_id) REFERENCES clients(id);