create SCHEMA IF NOT EXISTS university;


create TABLE IF NOT EXISTS university.student (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio VARCHAR NOT NULL,
    email VARCHAR NOT NULL,
    course VARCHAR NOT NULL
)

create TABLE IF NOT EXISTS university.student_x_course(
       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       studentId INT NOT NULL,
       courseId INT NOT NULL
)