-- Первая таблица
CREATE TABLE IF NOT EXISTS university.student (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio VARCHAR(255) NOT NULL, -- Указываем тип данных для каждого столбца
    email VARCHAR(255) NOT NULL,
    course VARCHAR(255) NOT NULL
);

-- Вторая таблица
CREATE TABLE IF NOT EXISTS university.student_x_course (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    studentId INT NOT NULL,
    courseId INT NOT NULL
);