create SCHEMA IF NOT EXISTS smartNotes;

create TABLE IF NOT EXISTS smartNotes.users (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar (50) NOT NULL,
    password varchar (255) NOT NULL,
    email varchar (255),
    role varchar (50) NOT NULL,
    registered timestamp NOT NULL
);