create SCHEMA IF NOT EXISTS university;


create TABLE IF NOT EXISTS university.student (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio VARCHAR NOT NULL,
    email VARCHAR NOT NULL,
    course VARCHAR NOT NULL
)

create TABLE IF NOT EXISTS university.student_x_course(
       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       studentId INT NOT NULL,
       courseId INT NOT NULL
)

CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(50) NOT NULL PRIMARY KEY,
    password VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS authorities (
    username VARCHAR(50) NOT NULL,
    authority VARCHAR(50) NOT NULL,
    CONSTRAINT fk_authorities_users FOREIGN KEY(username) REFERENCES users(username)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_auth_username ON authorities (username, authority);