create SCHEMA IF NOT EXISTS  uni;

CREATE TABLE IF NOT EXISTS uni.course (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    courseName VARCHAR NOT NULL,
    isActive boolean default false,
    startDate timestamp NOT NULL
)