drop SCHEMA IF EXISTS "tire" cascade;

create SCHEMA "tire";

create TABLE IF NOT EXISTS tire.clients (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name varchar(50) NOT NULL,
  midl_name varchar(50) NOT NULL,
  last_name varchar(50) NOT NULL,
  date_of_birth timestamp,
  phone_number varchar(18) NOT NULL
);

create TABLE IF NOT EXISTS tire.cars (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id int NOT NULL,
  car_name varchar(50) NOT NULL,
  car_model varchar(50) NOT NULL,
  car_number varchar(50) NOT NULL
);

create TABLE IF NOT EXISTS tire.clients_x_cars (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  car_id int NOT NULL,
  client_id int NOT NULL
);

create TABLE IF NOT EXISTS tire.orders (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  car_id int NOT NULL,
  cost_of_work int NOT NULL
);

alter table tire.cars add CONSTRAINT fk_cars_client FOREIGN KEY (client_id) REFERENCES tire.clients(id);
alter table tire.clients_x_cars add CONSTRAINT fk_clients_x_cars_car FOREIGN KEY (car_id) REFERENCES tire.cars(id);
alter table tire.clients_x_cars add CONSTRAINT fk_clients_x_cars_client FOREIGN KEY (client_id) REFERENCES tire.clients(id);
alter table tire.orders add CONSTRAINT fk_orders_car FOREIGN KEY (car_id) REFERENCES  tire.cars(id);
