create SCHEMA IF NOT EXISTS schemanotes;

create TABLE IF NOT EXISTS schemanotes.notes (
    id BIGINT  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userId BIGINT  NOT NULL,
    title varchar (255) NOT NULL,
    description varchar (510),
    isActual boolean NOT NULL,
    isArchive boolean NOT NULL,
    createDate date NOT NULL
);